### ISSUE TITLE
Adapt react hooks to the demos

### ISSUE THREAD

**Issue by young-trigold** [TeemuKoivisto/prosemirror-react-typescript-example#19]
I have been used react hooks to dev with prosemirror for months. there is class style in your demo. change it to hooks style hopefully.

**Comment by TeemuKoivisto** [comment]
Hey @young-trigold thanks for the feedback. As I said in the README the boilerplate here might not be up-to-date. I myself have basically switched to using Svelte for my own editor. But if I ever happen to take interest in updating this I'll probably use hooks only.

**Comment by young-trigold** [comment]
Thanks for your reply. Svelte is an interesting choice, you will work
better with it on rich text editor.

Teemu Koivisto ***@***.***> 于 2022年11月2日周三 21:05写道：
